# Generated by Django 6.0.7 on 2026-07-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('searching', 'Recherche en cours'), ('ranking', 'Classement en cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='finder.researchjob')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('authority_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('research_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='finder.researchresult')),
            ],
            options={
                'ordering': ['-authority_score'],
            },
        ),
    ]
