# Generated by Django 6.0.7 on 2026-08-05 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outilia',
            name='est_valide',
            field=models.BooleanField(default=True, verbose_name='Est validé'),
        ),
        migrations.AddField(
            model_name='outilia',
            name='soumis_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outils_soumis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scraperlog',
            name='temps_execution',
            field=models.FloatField(default=0.0, help_text="Durée d'exécution en secondes"),
        ),
    ]
