# Generated by Django 6.0.7 on 2026-08-05 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_avis_user_outilia_est_valide_outilia_soumis_par_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='outilia',
            name='est_valide',
            field=models.BooleanField(default=True, verbose_name="Est validé par l'admin"),
        ),
        migrations.AlterUniqueTogether(
            name='avis',
            unique_together={('outil', 'user')},
        ),
    ]
