# Generated by Django 6.0.7 on 2026-08-06 12:16

import django.db.models.deletion
import finder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_outilia_favoris_outilia_modified_at_projet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAccesPlus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text="Description interne (ex: 'Lot stage EMSI 2026').", max_length=200)),
                ('max_utilisations', models.PositiveIntegerField(default=1, help_text="Nombre maximum d'activations autorisées pour ce code.")),
                ('utilisations_actuelles', models.PositiveIntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, help_text="Laisser vide pour un code sans date d'expiration.", null=True)),
            ],
            options={
                'verbose_name': "Code d'accès Plus",
                'verbose_name_plural': "Codes d'accès Plus",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterModelOptions(
            name='avis',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='outilia',
            options={'ordering': ['-date_ajout'], 'verbose_name': 'Outil IA', 'verbose_name_plural': 'Outils IA'},
        ),
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Projet'},
        ),
        migrations.AlterModelOptions(
            name='researchjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tâche de recherche'},
        ),
        migrations.AlterModelOptions(
            name='researchresult',
            options={'ordering': ['rank'], 'verbose_name': 'Résultat de recherche'},
        ),
        migrations.AlterModelOptions(
            name='scraperlog',
            options={'ordering': ['-date_execution'], 'verbose_name': 'Journal de scraping', 'verbose_name_plural': 'Journaux de scraping'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code_plus_utilise',
            field=models.CharField(blank=True, max_length=50, verbose_name='Code Plus utilisé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='est_abonne_plus',
            field=models.BooleanField(default=False, help_text="Activé via un code d'invitation gratuit.", verbose_name='Abonné Finder Plus'),
        ),
        migrations.AlterField(
            model_name='outilia',
            name='est_valide',
            field=models.BooleanField(db_index=True, default=True, verbose_name="Est validé par l'admin"),
        ),
        migrations.AlterField(
            model_name='outilia',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='outils', to='finder.tag'),
        ),
        migrations.AlterField(
            model_name='researchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('searching', 'Recherche en cours'), ('ranking', 'Classement en cours'), ('completed', 'Terminé'), ('failed', 'Échec')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='FichierContexte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_original', models.CharField(help_text='Nom original du fichier avant téléversement.', max_length=255)),
                ('fichier', models.FileField(upload_to=finder.models._upload_context_path, validators=[finder.models._validate_extension, finder.models._validate_taille])),
                ('extension', models.CharField(max_length=20)),
                ('taille_octets', models.BigIntegerField(default=0)),
                ('hash_md5', models.CharField(blank=True, help_text='Hash MD5 du contenu — empêche les doublons.', max_length=32)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(blank=True, help_text='Projet auquel ce fichier est associé (facultatif).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers', to='finder.projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_contexte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier de contexte',
                'verbose_name_plural': 'Fichiers de contexte',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
