# Generated by Django 5.2.17 on 2026-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_profile_actionable_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='outilia',
            name='provenance',
            field=models.CharField(choices=[('catalogue', 'Catalogue officiel'), ('scraper', 'Robot de scraping'), ('community', 'Communauté')], db_index=True, default='catalogue', help_text="Origine de l'entrée : catalogue officiel, robot de scraping ou communauté.", max_length=20, verbose_name="Provenance de l'outil"),
        ),
    ]
