# Generated by Django 5.2.17 on 2026-08-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_dedupe_outilia_url_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outilia',
            name='url_site',
            field=models.URLField(unique=True),
        ),
    ]
