# Generated by Django 5.2.17 on 2026-08-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_researchjob_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='recherches_restantes',
            field=models.PositiveIntegerField(default=3, help_text="Nombre de recherches gratuites restantes avant l'activation du Plan Finder Plus (ignore pour les abonnés Plus).", verbose_name='Recherches restantes'),
        ),
    ]
